<a href="https://colab.research.google.com/github/Meharshitraj/Meharshitraj/blob/main/Election_sentiment_analysis__India.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [71]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as xp

loading data

In [72]:
modi = pd.read_csv("/content/modi_reviews.csv")
rahul = pd.read_csv("/content/rahul_reviews.csv")

In [73]:
modi.head()

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...
3,3,TheNirbhay1,PM Modi creates a new record of being the only...
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...

In [74]:
modi.shape

(25688, 3)

In [75]:
rahul.head()

,Unnamed: 0,User,Tweet
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ..."
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...

In [76]:
rahul.shape

(14261, 3)

In [77]:
TextBlob(modi["Tweet"][10]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [78]:
TextBlob(rahul["Tweet"][2]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [79]:
modi['Tweet'] = modi['Tweet'].astype(str)
rahul['Tweet'] = rahul['Tweet'].astype(str)

def find_polarity(review):
  return TextBlob(review).sentiment.polarity

In [80]:
modi['Polarity'] = modi['Tweet'].apply(find_polarity)
rahul['Polarity'] = rahul['Tweet'].apply(find_polarity)

In [81]:
modi

,Unnamed: 0,User,Tweet,Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542

In [82]:
rahul

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667
...,...,...,...,...
14256,14256,SunjayJK,"@quizzicalguy In this #LokSabhaElections2019, ...",0.000000
14257,14257,SunjayJK,@AnumaVidisha @RahulGandhi @ArvindKejriwal whe...,-0.500000
14258,14258,RAMANKAIRA,@sherryontopp Early morning #political move af...,0.080000
14259,14259,RAMANKAIRA,@mayankgandhi04 @mallesh_2004 Early morning #p...,0.080000
14260,14260,RAMANKAIRA,@DrKumarVishwas Early morning #political move ...,0.080000

In [83]:
modi['Label'] =  np.where(modi['Polarity'] > 0, 'Positive', 'Negative')
modi['Label'][modi['Polarity'] == 0] = 'Neutral'

rahul['Label'] =  np.where(rahul['Polarity'] > 0, 'Positive', 'Negative')
rahul['Label'][rahul['Polarity'] == 0] = 'Neutral'

/tmp/ipykernel_734/3854019799.py:2: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_734/3854019799.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_734/3854019799.py:5: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_734/3854019799.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [84]:
modi

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000,Positive
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121,Positive
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788,Positive
...,...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000,Neutral
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524,Positive
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000,Negative
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000,Neutral
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542,Negative

In [85]:
rahul

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750,Positive
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000,Neutral
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000,Neutral
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000,Positive
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667,Negative
...,...,...,...,...,...
14256,14256,SunjayJK,"@quizzicalguy In this #LokSabhaElections2019, ...",0.000000,Neutral
14257,14257,SunjayJK,@AnumaVidisha @RahulGandhi @ArvindKejriwal whe...,-0.500000,Negative
14258,14258,RAMANKAIRA,@sherryontopp Early morning #political move af...,0.080000,Positive
14259,14259,RAMANKAIRA,@mayankgandhi04 @mallesh_2004 Early morning #p...,0.080000,Positive
14260,14260,RAMANKAIRA,@DrKumarVishwas Early morning #political move ...,0.080000,Positive

In [86]:
neutral_modi = modi[modi['Polarity'] == 0.000]
remove_neutral_modi = modi['Polarity'] . isin(neutral_modi['Polarity'])
modi.drop(modi[remove_neutral_modi].index,inplace = True)

In [87]:
print(neutral_modi.shape)
print(modi.shape)

(8206, 5)
(17482, 5)

In [88]:
neutral_rahul = rahul[rahul['Polarity'] == 0.000]
remove_neutral_rahul = rahul['Polarity'] . isin(neutral_rahul['Polarity'])
rahul.drop(rahul[remove_neutral_rahul].index,inplace = True)

In [89]:
print(neutral_rahul.shape)
print(rahul.shape)

(4894, 5)
(9367, 5)

In [90]:
print(modi.shape)
print(rahul.shape)

(17482, 5)
(9367, 5)

In [91]:
# making row count to 9000
#for modi
np.random.seed(10)
remove_n = 8482
drop_indices = np.random.choice(modi.index, remove_n, replace=False)
df_modi = modi.drop(drop_indices)

In [92]:
print(df_modi.shape)

(9000, 5)

In [93]:
# for rahul
np.random.seed(10)
remove_n = 367
drop_indices = np.random.choice(rahul.index, remove_n, replace=False)
df_rahul = rahul.drop(drop_indices)

In [94]:
print(df_rahul.shape)

(9000, 5)

Prediction for election

In [95]:
modi_count = df_modi.groupby('Label').count()
modi_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        2629  2629   2629      2629
Positive        6371  6371   6371      6371

In [96]:
neg_modi = (modi_count['Polarity'][0] / 1000) *100
pos_modi = (modi_count['Polarity'][1] / 1000) *100

/tmp/ipykernel_734/627430650.py:1: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/tmp/ipykernel_734/627430650.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

In [97]:
rahul_count = df_rahul.groupby('Label').count()
rahul_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        3042  3042   3042      3042
Positive        5958  5958   5958      5958

In [98]:
neg_rahul = (rahul_count['Polarity'][0] / 1000) *100
pos_rahul = (rahul_count['Polarity'][1] / 1000) *100

/tmp/ipykernel_734/3707797696.py:1: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/tmp/ipykernel_734/3707797696.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

visualization

In [99]:
politicians = ['Modi','Rahul']

neg_list = [neg_modi,neg_rahul]
pos_list = [pos_modi,pos_rahul]

fig = go.Figure(data=[
    go.Bar(name='Negative', x=politicians, y=neg_list),
    go.Bar(name='Positive', x=politicians, y=pos_list)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()
#

Modi Again